### ISSUE TITLE
Schedule the "maintenance" task yearly

### ISSUE THREAD

**Issue by dskecse** [stachern/bseu_schedule#25]
The `/task/maintenance` task should be scheduled yearly instead of the long-deleted `/cleanup_sessions` task:

```yaml
cron:
...
- description: daily session cleanup
  url: /cleanup_sessions
  schedule: every 24 hours
```

to something like:

```yaml
cron:
...
- description: "perform maintenance (increment course, cleanup graduates and old links)"
  url: /task/maintenance
  schedule: 1st sunday of aug 11:00
```

It may be a good idea to combine `/task/maintenance` with `/task/cleanup` in some way.
